### ISSUE TITLE
Same play causes game to not progress.

### ISSUE THREAD

**Issue by qgevans** [spni/spni.github.io#21]
Myself and one of the AIs both had only a pair of twos, so the game simply stopped progressing.

**Comment by spni** [comment]
I am aware of this issue, but wasn't aware that it would completely stop the game. Thank you for letting me know, I'll try to fix it in my next update.

**Comment by spni** [comment]
I believe that I have found and fixed the issue as of version 10.6.1. The chances of a perfect tie are very rare, but the game should not come to a complete stop if it ever happens again.
