### ISSUE TITLE
Error: couldn't find finishing_masturbating dialogue for...

### ISSUE THREAD

**Issue by ghost** [spni/spni.github.io#22]
Every so often, the game fires off this error after a player has finished. I can confirm that it happens for Daisy, Wii Fit Trainer and my custom characters. 

It appears that it is looking for a finishing_masturbating state for when the character has already finished. 

Using offline version from master branch, ver 10.5.0 in Firefox.

**Comment by ghost** [comment]
Screen shot
![image](https://cloud.githubusercontent.com/assets/3926635/18059025/053d6a22-6de5-11e6-9bf4-d92594196c7d.png)

**Comment by spni** [comment]
One of the triggers may be mis-labelled. Thank you for letting me know, I'll look into it. 
Also, it looks like Miss Pauling is going well.

**Comment by ghost** [comment]
Thanks! Sorry for the spam of issues, I have been play testing Pauling this weekend and found a couple that stuck out.

**Comment by spni** [comment]
Please, if you find any more issues, report them. I don't have a lot of time to work on the game, but when I do, it helps to know what needs work.

**Comment by spni** [comment]
I believe that I've found and fixed the issue as of version 10.6.1. Although there is no particularly good state to put opponents in during that phase of the game, so it may seem a little strange.

**Comment by ghost** [comment]
Alright. I agree, It does look a bit strange with characters that sit to forfeit as they go from standing when finished to sitting for one case. Maybe there is a need for an addition case in stage 9?
Thanks.
