### ISSUE TITLE
Duplicate cards

### ISSUE THREAD

**Issue by ghost** [spni/spni.github.io#23]
I received duplicate cards.

![capture](https://cloud.githubusercontent.com/assets/3926635/18059184/cc5499dc-6de5-11e6-8b60-4ffb9b0dce75.PNG)

Using offline version from master branch, ver 10.5.0 in Firefox.

**Comment by spni** [comment]
I believe that I fixed this in version 10.6.0, which is the newest version. If you see it happen in 10.6.0, please let me know.
