### ISSUE TITLE
Stage 7 case stripped does not generate in the behaviour.xml.

### ISSUE THREAD

**Issue by ghost** [spni/spni.github.io#24]
This may not be a bug, and it is definitely not that important as there is a quick way to fix it. 

When I include a stripped case for stage 7 in my behavior.txt then transfer it to the XML via make_xml.py, a stripped case is not generated for stage 7. I know daisy's character uses it and I have been able to use it in game if I add it in by hand to the XML. 

Included are both files, before any modification to get stage 7 case stripped to work (GitHub would not accept .xml, so I have provided behaviour.xml in plain text)
[pauling_behaviour.txt](https://github.com/spni/spni.github.io/files/443887/pauling_behaviour.txt)
[behaviour.txt](https://github.com/spni/spni.github.io/files/443889/behaviour.txt)

Thanks for all the hard work! This game looks better everyday!

**Comment by Zombiqaz** [comment]
I found and fixed the bug in the make_xml.py file.

(It was from some earlier work where I made the script put fewer unused entries into the final xml file, but removed one case too many. I also allowed the script to work when a character's attributes where empty.)
